#!/bin/bash
# Project build file

if uname -a | grep -q Darwin; then
    # Build on mac
    LOCK_DIR='/Users/zhang/Dropbox/UMich2020sp/pitometer/measurements/toylock/toylock-go'
    export GOPATH=$LOCK_DIR

    echo "Starting ToyLock OSX build"

    go build -o toylock-main "$LOCK_DIR/src/Main.go" 

    export GOPATH='/Users/zhang/go'
    export PATH=$PATH:$(go env GOPATH)/bin
    export GOPATH=$(go env GOPATH)
elif uname -a | grep -q Linux; then
    # Build on Linux
    export GO111MODULE=off
    LOCK_DIR='/home/nudzhang/Documents/pitometer/measurements/toylock/toylock-go'
    export GOPATH=$LOCK_DIR

    echo "Starting ToyLock Linux build"
    go env GOPATH

    go build -o toylock-main "$LOCK_DIR/src/Main.go" 

    # export GOPATH='/home/nudzhang/go'
    # export PATH=$PATH:$(go env GOPATH)/bin
    # export GOPATH=$(go env GOPATH)
else
    echo "Build failed"
    exit 1
fi
echo "Build complete"



#/home/nudzhang/sdk/go1.16.2