#!/bin/bash
# Project build file for mac

LOCK_DIR='/Users/zhang/Dropbox/UMich2020sp/pitometer/measurements/toylock/toylock-go'
export GOPATH=$LOCK_DIR

echo "Starting build"

go build -o toylock-main "$LOCK_DIR/src/Main.go" 

export GOPATH='/Users/zhang/go'
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)

echo "Build complete"
