#!/bin/bash
# WARNING: Breaks when 'find' returns filenames with whitespace characters

RAWFILES=(`find ./data -type f -name *.raw`)
CSVFILES=""

for rf in "${RAWFILES[@]}"
do :
    echo $rf
    DIR=$(dirname "${rf}")      # directory name
    NAME=$(basename -- "$rf")
    EXT="${NAME##*.}"          
    NAME="${NAME%.*}"           # filename without extension

    CSV=$DIR/$NAME.csv
    cat $rf | grep "Node" > $CSV
    CSVFILES="$CSVFILES $CSV"
done

python3 analyze.py $CSVFILES