#!/bin/bash
# Project build file for linux

LOCK_DIR='/home/nudzhang/Documents/pitometer/go-compiler/toylock-go'
export GOPATH=$LOCK_DIR

go build -o toylock-main "$LOCK_DIR/src/Main.go" 

export GOPATH='/home/nudzhang/go'
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)
