#!/bin/bash
# Project build file for linux

RSL_DIR='/home/nudzhang/Documents/pitometer/measurements/rsl/rsl-go'
export GOPATH=$RSL_DIR

echo "Starting build"

go build -o rsl-main "$RSL_DIR/src/Main.go" 

export GOPATH='/home/nudzhang/go'
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)

echo "Build complete"
